version: "2"

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck

run:
  timeout: 5m
